fiducials:
  -
    id: 1
    z: 2.735
    x: 0.285
    y: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  - 
    id: 1
    x: 2.735
    y: 0.0
    z: 0.0
    roll: 0
    pitch: 0
    yaw: 0
  -
    id: 2
    x: 2.735
    y: -0.305
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  -
    id: 3
    x: -2.735
    y: -0.305
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
  -
    id: 4
    x: -2.735
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0

  -
    id: 5
    x: -2.735
    y: 0.285
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
  -
    id: 6
    x: -2.735
    y: 0.285
    z: 0
    roll: 0
    pitch: 0
    yaw: 0