# NavigateAprilTags.action

# Goal
geometry_msgs/PoseStamped[] goals                 # List of Poses (each with a reference coordinate frame and a timestamp)
string[] commands            # Commands for each tag ("vertical", "left", "right", "finish")
---
# Result
bool navigation_completed                 # Whether the navigation sequence completed successfully
---
# Feedback
geometry_msgs/PoseStamped next_pose           # The next goal pose
string next_command       # The next command to execute